apiVersion: apps/v1
kind: Deployment
metadata:
  name: conner-backend
  namespace: conner
  labels:
    app: conner-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conner-backend
  template:
    metadata:
      labels:
        app: conner-backend
    spec:
      containers:
        - name: conner-backend
          image: ghcr.io/motung-i/motung-backend:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 400m
              memory: 1536Mi
            requests:
              cpu: 200m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          envFrom:
            - secretRef:
                name: conner-backend
