apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: conner-backend-ingress
  namespace: conner
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: conner-api.mya.ong
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: conner-backend
                port:
                  number: 80
  tls:
    - hosts:
        - conner-api.mya.ong
      secretName: conner-backend-tls
