apiVersion: v1
kind: Service
metadata:
  name: conner-backend
  namespace: conner
spec:
  selector:
    app: conner-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: monitoring
      port: 8081
      targetPort: 8081
  type: ClusterIP
